name: homework
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  provider: ^6.0.5
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  circle_flags: ^3.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true

  assets:
    - assets/images/

  uses-material-design: true
