name: homework
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  circle_flags: ^3.0.1
  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true

  assets:
    - assets/images/

  uses-material-design: true
